version: '3'

services:
  minio:
    image: minio/minio:latest
    platform: linux/amd64
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio_password}
    volumes:
      - ./minio/data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -e
        echo "Waiting MinIO..."
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        echo "Creating bucket '${BUCKET_NAME}' if not exists..."
        mc mb -p local/${BUCKET_NAME} || true
        echo "Bucket ready."
    restart: "no"

  nginx:
    image: nginx:latest
    platform: linux/amd64
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./nginx/logs:/var/log/nginx:ro
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - ./vector/state:/var/lib/vector
    command: ["--config", "/etc/vector/vector.toml"]
    environment:
      BUCKET_NAME: ${BUCKET_NAME:-nginx-logs}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio_password}
      NGINX_SLACK_WEBHOOK_URL: ${NGINX_SLACK_WEBHOOK_URL}
      